//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGASQLI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demande
    {
        public int id { get; set; }
        public System.DateTime dateCreation { get; set; }
        public Nullable<System.DateTime> dateDebutTraitement { get; set; }
        public Nullable<System.DateTime> dateFinTraitement { get; set; }
    
        public virtual Statut Statut { get; set; }
        public virtual TypeAttestation TypeAttestation { get; set; }
        public virtual Collaborateur Collaborateur { get; set; }
        public virtual Collaborateur Assistante { get; set; }
    }
}
