//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGASQLI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextContainer : DbContext
    {
        public ContextContainer()
            : base("name=ContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Demande> DemandeSet { get; set; }
        public virtual DbSet<Statut> StatutSet { get; set; }
        public virtual DbSet<TypeAttestation> TypeAttestationSet { get; set; }
        public virtual DbSet<Collaborateur> CollaborateurSet { get; set; }
    }
}
