//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGASQLI.ServiceDemande {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDemande.ITraiterDemande")]
    public interface ITraiterDemande {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/GetDemandesEnAttenteList", ReplyAction="http://tempuri.org/ITraiterDemande/GetDemandesEnAttenteListResponse")]
        AGA.DTO.Models.Demande[] GetDemandesEnAttenteList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/GetDemandesEnAttenteList", ReplyAction="http://tempuri.org/ITraiterDemande/GetDemandesEnAttenteListResponse")]
        System.Threading.Tasks.Task<AGA.DTO.Models.Demande[]> GetDemandesEnAttenteListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/GetNombreDemandesEnAttente", ReplyAction="http://tempuri.org/ITraiterDemande/GetNombreDemandesEnAttenteResponse")]
        int GetNombreDemandesEnAttente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/GetNombreDemandesEnAttente", ReplyAction="http://tempuri.org/ITraiterDemande/GetNombreDemandesEnAttenteResponse")]
        System.Threading.Tasks.Task<int> GetNombreDemandesEnAttenteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/GetDemandesListParCollaborateur", ReplyAction="http://tempuri.org/ITraiterDemande/GetDemandesListParCollaborateurResponse")]
        AGA.DTO.Models.Demande[] GetDemandesListParCollaborateur(int idCollaborateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/GetDemandesListParCollaborateur", ReplyAction="http://tempuri.org/ITraiterDemande/GetDemandesListParCollaborateurResponse")]
        System.Threading.Tasks.Task<AGA.DTO.Models.Demande[]> GetDemandesListParCollaborateurAsync(int idCollaborateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/GetDemandesEnCoursParAssistante", ReplyAction="http://tempuri.org/ITraiterDemande/GetDemandesEnCoursParAssistanteResponse")]
        AGA.DTO.Models.Demande[] GetDemandesEnCoursParAssistante(int idAssistante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/GetDemandesEnCoursParAssistante", ReplyAction="http://tempuri.org/ITraiterDemande/GetDemandesEnCoursParAssistanteResponse")]
        System.Threading.Tasks.Task<AGA.DTO.Models.Demande[]> GetDemandesEnCoursParAssistanteAsync(int idAssistante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/AjouterDemandesListAssistante", ReplyAction="http://tempuri.org/ITraiterDemande/AjouterDemandesListAssistanteResponse")]
        void AjouterDemandesListAssistante(AGA.DTO.Models.Demande[] demandesList, int idAssistante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/AjouterDemandesListAssistante", ReplyAction="http://tempuri.org/ITraiterDemande/AjouterDemandesListAssistanteResponse")]
        System.Threading.Tasks.Task AjouterDemandesListAssistanteAsync(AGA.DTO.Models.Demande[] demandesList, int idAssistante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutEnCours", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutEnCoursResponse")]
        void ChangerStatutEnCours(AGA.DTO.Models.Demande demande);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutEnCours", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutEnCoursResponse")]
        System.Threading.Tasks.Task ChangerStatutEnCoursAsync(AGA.DTO.Models.Demande demande);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutEnCoursList", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutEnCoursListResponse")]
        void ChangerStatutEnCoursList(AGA.DTO.Models.Demande[] demandesList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutEnCoursList", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutEnCoursListResponse")]
        System.Threading.Tasks.Task ChangerStatutEnCoursListAsync(AGA.DTO.Models.Demande[] demandesList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutPrete", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutPreteResponse")]
        void ChangerStatutPrete(AGA.DTO.Models.Demande demande);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutPrete", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutPreteResponse")]
        System.Threading.Tasks.Task ChangerStatutPreteAsync(AGA.DTO.Models.Demande demande);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutPreteList", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutPreteListResponse")]
        void ChangerStatutPreteList(AGA.DTO.Models.Demande[] demandesList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutPreteList", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutPreteListResponse")]
        System.Threading.Tasks.Task ChangerStatutPreteListAsync(AGA.DTO.Models.Demande[] demandesList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutRejetee", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutRejeteeResponse")]
        void ChangerStatutRejetee(AGA.DTO.Models.Demande demande);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutRejetee", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutRejeteeResponse")]
        System.Threading.Tasks.Task ChangerStatutRejeteeAsync(AGA.DTO.Models.Demande demande);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutRejeteeList", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutRejeteeListResponse")]
        void ChangerStatutRejeteeList(AGA.DTO.Models.Demande[] demandesList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterDemande/ChangerStatutRejeteeList", ReplyAction="http://tempuri.org/ITraiterDemande/ChangerStatutRejeteeListResponse")]
        System.Threading.Tasks.Task ChangerStatutRejeteeListAsync(AGA.DTO.Models.Demande[] demandesList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITraiterDemandeChannel : AGASQLI.ServiceDemande.ITraiterDemande, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TraiterDemandeClient : System.ServiceModel.ClientBase<AGASQLI.ServiceDemande.ITraiterDemande>, AGASQLI.ServiceDemande.ITraiterDemande {
        
        public TraiterDemandeClient() {
        }
        
        public TraiterDemandeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TraiterDemandeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraiterDemandeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraiterDemandeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AGA.DTO.Models.Demande[] GetDemandesEnAttenteList() {
            return base.Channel.GetDemandesEnAttenteList();
        }
        
        public System.Threading.Tasks.Task<AGA.DTO.Models.Demande[]> GetDemandesEnAttenteListAsync() {
            return base.Channel.GetDemandesEnAttenteListAsync();
        }
        
        public int GetNombreDemandesEnAttente() {
            return base.Channel.GetNombreDemandesEnAttente();
        }
        
        public System.Threading.Tasks.Task<int> GetNombreDemandesEnAttenteAsync() {
            return base.Channel.GetNombreDemandesEnAttenteAsync();
        }
        
        public AGA.DTO.Models.Demande[] GetDemandesListParCollaborateur(int idCollaborateur) {
            return base.Channel.GetDemandesListParCollaborateur(idCollaborateur);
        }
        
        public System.Threading.Tasks.Task<AGA.DTO.Models.Demande[]> GetDemandesListParCollaborateurAsync(int idCollaborateur) {
            return base.Channel.GetDemandesListParCollaborateurAsync(idCollaborateur);
        }
        
        public AGA.DTO.Models.Demande[] GetDemandesEnCoursParAssistante(int idAssistante) {
            return base.Channel.GetDemandesEnCoursParAssistante(idAssistante);
        }
        
        public System.Threading.Tasks.Task<AGA.DTO.Models.Demande[]> GetDemandesEnCoursParAssistanteAsync(int idAssistante) {
            return base.Channel.GetDemandesEnCoursParAssistanteAsync(idAssistante);
        }
        
        public void AjouterDemandesListAssistante(AGA.DTO.Models.Demande[] demandesList, int idAssistante) {
            base.Channel.AjouterDemandesListAssistante(demandesList, idAssistante);
        }
        
        public System.Threading.Tasks.Task AjouterDemandesListAssistanteAsync(AGA.DTO.Models.Demande[] demandesList, int idAssistante) {
            return base.Channel.AjouterDemandesListAssistanteAsync(demandesList, idAssistante);
        }
        
        public void ChangerStatutEnCours(AGA.DTO.Models.Demande demande) {
            base.Channel.ChangerStatutEnCours(demande);
        }
        
        public System.Threading.Tasks.Task ChangerStatutEnCoursAsync(AGA.DTO.Models.Demande demande) {
            return base.Channel.ChangerStatutEnCoursAsync(demande);
        }
        
        public void ChangerStatutEnCoursList(AGA.DTO.Models.Demande[] demandesList) {
            base.Channel.ChangerStatutEnCoursList(demandesList);
        }
        
        public System.Threading.Tasks.Task ChangerStatutEnCoursListAsync(AGA.DTO.Models.Demande[] demandesList) {
            return base.Channel.ChangerStatutEnCoursListAsync(demandesList);
        }
        
        public void ChangerStatutPrete(AGA.DTO.Models.Demande demande) {
            base.Channel.ChangerStatutPrete(demande);
        }
        
        public System.Threading.Tasks.Task ChangerStatutPreteAsync(AGA.DTO.Models.Demande demande) {
            return base.Channel.ChangerStatutPreteAsync(demande);
        }
        
        public void ChangerStatutPreteList(AGA.DTO.Models.Demande[] demandesList) {
            base.Channel.ChangerStatutPreteList(demandesList);
        }
        
        public System.Threading.Tasks.Task ChangerStatutPreteListAsync(AGA.DTO.Models.Demande[] demandesList) {
            return base.Channel.ChangerStatutPreteListAsync(demandesList);
        }
        
        public void ChangerStatutRejetee(AGA.DTO.Models.Demande demande) {
            base.Channel.ChangerStatutRejetee(demande);
        }
        
        public System.Threading.Tasks.Task ChangerStatutRejeteeAsync(AGA.DTO.Models.Demande demande) {
            return base.Channel.ChangerStatutRejeteeAsync(demande);
        }
        
        public void ChangerStatutRejeteeList(AGA.DTO.Models.Demande[] demandesList) {
            base.Channel.ChangerStatutRejeteeList(demandesList);
        }
        
        public System.Threading.Tasks.Task ChangerStatutRejeteeListAsync(AGA.DTO.Models.Demande[] demandesList) {
            return base.Channel.ChangerStatutRejeteeListAsync(demandesList);
        }
    }
}
