//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGASQLI.WorkflowAjouterAMesTaches {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AjouterDonnees", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AjouterDonnees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AGA.Common.DTO.Models.Demande[] demandesListEntreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAssistanteEntreeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AGA.Common.DTO.Models.Demande[] demandesListEntree {
            get {
                return this.demandesListEntreeField;
            }
            set {
                if ((object.ReferenceEquals(this.demandesListEntreeField, value) != true)) {
                    this.demandesListEntreeField = value;
                    this.RaisePropertyChanged("demandesListEntree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAssistanteEntree {
            get {
                return this.idAssistanteEntreeField;
            }
            set {
                if ((this.idAssistanteEntreeField.Equals(value) != true)) {
                    this.idAssistanteEntreeField = value;
                    this.RaisePropertyChanged("idAssistanteEntree");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkflowAjouterAMesTaches.IAjouterAMesTaches")]
    public interface IAjouterAMesTaches {
        
        // CODEGEN : La génération du contrat de message depuis l'opération AjouterDonnees n'est ni RPC, ni encapsulée dans un document.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAjouterAMesTaches/AjouterDonnees", ReplyAction="http://tempuri.org/IAjouterAMesTaches/AjouterDonneesResponse")]
        AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesResponse AjouterDonnees(AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAjouterAMesTaches/AjouterDonnees", ReplyAction="http://tempuri.org/IAjouterAMesTaches/AjouterDonneesResponse")]
        System.Threading.Tasks.Task<AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesResponse> AjouterDonneesAsync(AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AjouterDonneesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AGASQLI.WorkflowAjouterAMesTaches.AjouterDonnees AjouterDonnees;
        
        public AjouterDonneesRequest() {
        }
        
        public AjouterDonneesRequest(AGASQLI.WorkflowAjouterAMesTaches.AjouterDonnees AjouterDonnees) {
            this.AjouterDonnees = AjouterDonnees;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AjouterDonneesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public string @string;
        
        public AjouterDonneesResponse() {
        }
        
        public AjouterDonneesResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAjouterAMesTachesChannel : AGASQLI.WorkflowAjouterAMesTaches.IAjouterAMesTaches, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AjouterAMesTachesClient : System.ServiceModel.ClientBase<AGASQLI.WorkflowAjouterAMesTaches.IAjouterAMesTaches>, AGASQLI.WorkflowAjouterAMesTaches.IAjouterAMesTaches {
        
        public AjouterAMesTachesClient() {
        }
        
        public AjouterAMesTachesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AjouterAMesTachesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AjouterAMesTachesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AjouterAMesTachesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesResponse AGASQLI.WorkflowAjouterAMesTaches.IAjouterAMesTaches.AjouterDonnees(AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesRequest request) {
            return base.Channel.AjouterDonnees(request);
        }
        
        public string AjouterDonnees(AGASQLI.WorkflowAjouterAMesTaches.AjouterDonnees AjouterDonnees1) {
            AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesRequest inValue = new AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesRequest();
            inValue.AjouterDonnees = AjouterDonnees1;
            AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesResponse retVal = ((AGASQLI.WorkflowAjouterAMesTaches.IAjouterAMesTaches)(this)).AjouterDonnees(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesResponse> AGASQLI.WorkflowAjouterAMesTaches.IAjouterAMesTaches.AjouterDonneesAsync(AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesRequest request) {
            return base.Channel.AjouterDonneesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesResponse> AjouterDonneesAsync(AGASQLI.WorkflowAjouterAMesTaches.AjouterDonnees AjouterDonnees) {
            AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesRequest inValue = new AGASQLI.WorkflowAjouterAMesTaches.AjouterDonneesRequest();
            inValue.AjouterDonnees = AjouterDonnees;
            return ((AGASQLI.WorkflowAjouterAMesTaches.IAjouterAMesTaches)(this)).AjouterDonneesAsync(inValue);
        }
    }
}
