//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGASQLI.ServiceAttestation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HttpResponse", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.AspNet.Http")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.IO.MemoryStream))]
    public partial class HttpResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.Stream BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ContentLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.Stream Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ContentLength {
            get {
                return this.ContentLengthField;
            }
            set {
                if ((this.ContentLengthField.Equals(value) != true)) {
                    this.ContentLengthField = value;
                    this.RaisePropertyChanged("ContentLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((this.StatusCodeField.Equals(value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAttestation.ITraiterAttestation")]
    public interface ITraiterAttestation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationConge", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationCongeResponse")]
        System.IO.MemoryStream GenererAttestationConge(AGA.Common.DTO.Models.AttestationConge attestationConge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationConge", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationCongeResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationCongeAsync(AGA.Common.DTO.Models.AttestationConge attestationConge);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationIrrevocableSalaire", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationIrrevocableSalaireRespon" +
            "se")]
        System.IO.MemoryStream GenererAttestationIrrevocableSalaire(AGA.Common.Entities.AttestationIrrevocableSalaire attestationIrrevocableSalaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationIrrevocableSalaire", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationIrrevocableSalaireRespon" +
            "se")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationIrrevocableSalaireAsync(AGA.Common.Entities.AttestationIrrevocableSalaire attestationIrrevocableSalaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationSalaire", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationSalaireResponse")]
        System.IO.MemoryStream GenererAttestationSalaire(AGA.Common.Entities.AttestationSalaire attestationSalaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationSalaire", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationSalaireResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationSalaireAsync(AGA.Common.Entities.AttestationSalaire attestationSalaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationStage", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationStageResponse")]
        System.IO.MemoryStream GenererAttestationStage(AGA.Common.Entities.AttestationStage attestationStage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationStage", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationStageResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationStageAsync(AGA.Common.Entities.AttestationStage attestationStage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationTravail", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationTravailResponse")]
        System.IO.MemoryStream GenererAttestationTravail(AGA.Common.Entities.AttestationTravail attestationTravail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAttestationTravail", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAttestationTravailResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationTravailAsync(AGA.Common.Entities.AttestationTravail attestationTravail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAutorisationCoursVacation", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAutorisationCoursVacationResponse")]
        System.IO.MemoryStream GenererAutorisationCoursVacation(AGA.Common.DTO.Models.AutorisationCoursVacation autorisationCoursVacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererAutorisationCoursVacation", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererAutorisationCoursVacationResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAutorisationCoursVacationAsync(AGA.Common.DTO.Models.AutorisationCoursVacation autorisationCoursVacation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenrerAutorisationPoursuiteEtudes", ReplyAction="http://tempuri.org/ITraiterAttestation/GenrerAutorisationPoursuiteEtudesResponse")]
        System.IO.MemoryStream GenrerAutorisationPoursuiteEtudes(AGA.Common.DTO.Models.AutorisationPoursuiteEtudes autorisationPoursuiteEtudes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenrerAutorisationPoursuiteEtudes", ReplyAction="http://tempuri.org/ITraiterAttestation/GenrerAutorisationPoursuiteEtudesResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> GenrerAutorisationPoursuiteEtudesAsync(AGA.Common.DTO.Models.AutorisationPoursuiteEtudes autorisationPoursuiteEtudes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererReponseLettreDemission", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererReponseLettreDemissionResponse")]
        System.IO.MemoryStream GenererReponseLettreDemission(AGA.Common.Entities.ReponseLettreDemission reponseLettreDemission);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/GenererReponseLettreDemission", ReplyAction="http://tempuri.org/ITraiterAttestation/GenererReponseLettreDemissionResponse")]
        System.Threading.Tasks.Task<System.IO.MemoryStream> GenererReponseLettreDemissionAsync(AGA.Common.Entities.ReponseLettreDemission reponseLettreDemission);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/Telecharger", ReplyAction="http://tempuri.org/ITraiterAttestation/TelechargerResponse")]
        void Telecharger(AGASQLI.ServiceAttestation.HttpResponse Response, System.IO.MemoryStream documentStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterAttestation/Telecharger", ReplyAction="http://tempuri.org/ITraiterAttestation/TelechargerResponse")]
        System.Threading.Tasks.Task TelechargerAsync(AGASQLI.ServiceAttestation.HttpResponse Response, System.IO.MemoryStream documentStream);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITraiterAttestationChannel : AGASQLI.ServiceAttestation.ITraiterAttestation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TraiterAttestationClient : System.ServiceModel.ClientBase<AGASQLI.ServiceAttestation.ITraiterAttestation>, AGASQLI.ServiceAttestation.ITraiterAttestation {
        
        public TraiterAttestationClient() {
        }
        
        public TraiterAttestationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TraiterAttestationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraiterAttestationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraiterAttestationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.MemoryStream GenererAttestationConge(AGA.Common.DTO.Models.AttestationConge attestationConge) {
            return base.Channel.GenererAttestationConge(attestationConge);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationCongeAsync(AGA.Common.DTO.Models.AttestationConge attestationConge) {
            return base.Channel.GenererAttestationCongeAsync(attestationConge);
        }
        
        public System.IO.MemoryStream GenererAttestationIrrevocableSalaire(AGA.Common.Entities.AttestationIrrevocableSalaire attestationIrrevocableSalaire) {
            return base.Channel.GenererAttestationIrrevocableSalaire(attestationIrrevocableSalaire);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationIrrevocableSalaireAsync(AGA.Common.Entities.AttestationIrrevocableSalaire attestationIrrevocableSalaire) {
            return base.Channel.GenererAttestationIrrevocableSalaireAsync(attestationIrrevocableSalaire);
        }
        
        public System.IO.MemoryStream GenererAttestationSalaire(AGA.Common.Entities.AttestationSalaire attestationSalaire) {
            return base.Channel.GenererAttestationSalaire(attestationSalaire);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationSalaireAsync(AGA.Common.Entities.AttestationSalaire attestationSalaire) {
            return base.Channel.GenererAttestationSalaireAsync(attestationSalaire);
        }
        
        public System.IO.MemoryStream GenererAttestationStage(AGA.Common.Entities.AttestationStage attestationStage) {
            return base.Channel.GenererAttestationStage(attestationStage);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationStageAsync(AGA.Common.Entities.AttestationStage attestationStage) {
            return base.Channel.GenererAttestationStageAsync(attestationStage);
        }
        
        public System.IO.MemoryStream GenererAttestationTravail(AGA.Common.Entities.AttestationTravail attestationTravail) {
            return base.Channel.GenererAttestationTravail(attestationTravail);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAttestationTravailAsync(AGA.Common.Entities.AttestationTravail attestationTravail) {
            return base.Channel.GenererAttestationTravailAsync(attestationTravail);
        }
        
        public System.IO.MemoryStream GenererAutorisationCoursVacation(AGA.Common.DTO.Models.AutorisationCoursVacation autorisationCoursVacation) {
            return base.Channel.GenererAutorisationCoursVacation(autorisationCoursVacation);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> GenererAutorisationCoursVacationAsync(AGA.Common.DTO.Models.AutorisationCoursVacation autorisationCoursVacation) {
            return base.Channel.GenererAutorisationCoursVacationAsync(autorisationCoursVacation);
        }
        
        public System.IO.MemoryStream GenrerAutorisationPoursuiteEtudes(AGA.Common.DTO.Models.AutorisationPoursuiteEtudes autorisationPoursuiteEtudes) {
            return base.Channel.GenrerAutorisationPoursuiteEtudes(autorisationPoursuiteEtudes);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> GenrerAutorisationPoursuiteEtudesAsync(AGA.Common.DTO.Models.AutorisationPoursuiteEtudes autorisationPoursuiteEtudes) {
            return base.Channel.GenrerAutorisationPoursuiteEtudesAsync(autorisationPoursuiteEtudes);
        }
        
        public System.IO.MemoryStream GenererReponseLettreDemission(AGA.Common.Entities.ReponseLettreDemission reponseLettreDemission) {
            return base.Channel.GenererReponseLettreDemission(reponseLettreDemission);
        }
        
        public System.Threading.Tasks.Task<System.IO.MemoryStream> GenererReponseLettreDemissionAsync(AGA.Common.Entities.ReponseLettreDemission reponseLettreDemission) {
            return base.Channel.GenererReponseLettreDemissionAsync(reponseLettreDemission);
        }
        
        public void Telecharger(AGASQLI.ServiceAttestation.HttpResponse Response, System.IO.MemoryStream documentStream) {
            base.Channel.Telecharger(Response, documentStream);
        }
        
        public System.Threading.Tasks.Task TelechargerAsync(AGASQLI.ServiceAttestation.HttpResponse Response, System.IO.MemoryStream documentStream) {
            return base.Channel.TelechargerAsync(Response, documentStream);
        }
    }
}
