//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGASQLI.ServiceCollaborateur {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCollaborateur.ITraiterCollaborateur")]
    public interface ITraiterCollaborateur {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetEmail", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetEmailResponse")]
        string GetEmail(AGA.Common.DTO.Models.Collaborateur collaborateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetEmail", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetEmailResponse")]
        System.Threading.Tasks.Task<string> GetEmailAsync(AGA.Common.DTO.Models.Collaborateur collaborateur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetEmailList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetEmailListResponse")]
        string[] GetEmailList(AGA.Common.DTO.Models.Collaborateur[] collaborateurList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetEmailList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetEmailListResponse")]
        System.Threading.Tasks.Task<string[]> GetEmailListAsync(AGA.Common.DTO.Models.Collaborateur[] collaborateurList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetAssistantesList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetAssistantesListResponse")]
        AGA.Common.DTO.Models.Collaborateur[] GetAssistantesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetAssistantesList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetAssistantesListResponse")]
        System.Threading.Tasks.Task<AGA.Common.DTO.Models.Collaborateur[]> GetAssistantesListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetStagiairesList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetStagiairesListResponse")]
        AGA.Common.DTO.Models.Stagiaire[] GetStagiairesList(System.IO.FileStream fichierExcel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetStagiairesList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetStagiairesListResponse")]
        System.Threading.Tasks.Task<AGA.Common.DTO.Models.Stagiaire[]> GetStagiairesListAsync(System.IO.FileStream fichierExcel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetStagiairesPfeList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetStagiairesPfeListResponse")]
        AGA.Common.DTO.Models.Stagiaire[] GetStagiairesPfeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetStagiairesPfeList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetStagiairesPfeListResponse")]
        System.Threading.Tasks.Task<AGA.Common.DTO.Models.Stagiaire[]> GetStagiairesPfeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetCollaborateursNonEligiblesList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetCollaborateursNonEligiblesListRespons" +
            "e")]
        AGA.Common.DTO.Models.Collaborateur[] GetCollaborateursNonEligiblesList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITraiterCollaborateur/GetCollaborateursNonEligiblesList", ReplyAction="http://tempuri.org/ITraiterCollaborateur/GetCollaborateursNonEligiblesListRespons" +
            "e")]
        System.Threading.Tasks.Task<AGA.Common.DTO.Models.Collaborateur[]> GetCollaborateursNonEligiblesListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITraiterCollaborateurChannel : AGASQLI.ServiceCollaborateur.ITraiterCollaborateur, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TraiterCollaborateurClient : System.ServiceModel.ClientBase<AGASQLI.ServiceCollaborateur.ITraiterCollaborateur>, AGASQLI.ServiceCollaborateur.ITraiterCollaborateur {
        
        public TraiterCollaborateurClient() {
        }
        
        public TraiterCollaborateurClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TraiterCollaborateurClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraiterCollaborateurClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TraiterCollaborateurClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetEmail(AGA.Common.DTO.Models.Collaborateur collaborateur) {
            return base.Channel.GetEmail(collaborateur);
        }
        
        public System.Threading.Tasks.Task<string> GetEmailAsync(AGA.Common.DTO.Models.Collaborateur collaborateur) {
            return base.Channel.GetEmailAsync(collaborateur);
        }
        
        public string[] GetEmailList(AGA.Common.DTO.Models.Collaborateur[] collaborateurList) {
            return base.Channel.GetEmailList(collaborateurList);
        }
        
        public System.Threading.Tasks.Task<string[]> GetEmailListAsync(AGA.Common.DTO.Models.Collaborateur[] collaborateurList) {
            return base.Channel.GetEmailListAsync(collaborateurList);
        }
        
        public AGA.Common.DTO.Models.Collaborateur[] GetAssistantesList() {
            return base.Channel.GetAssistantesList();
        }
        
        public System.Threading.Tasks.Task<AGA.Common.DTO.Models.Collaborateur[]> GetAssistantesListAsync() {
            return base.Channel.GetAssistantesListAsync();
        }
        
        public AGA.Common.DTO.Models.Stagiaire[] GetStagiairesList(System.IO.FileStream fichierExcel) {
            return base.Channel.GetStagiairesList(fichierExcel);
        }
        
        public System.Threading.Tasks.Task<AGA.Common.DTO.Models.Stagiaire[]> GetStagiairesListAsync(System.IO.FileStream fichierExcel) {
            return base.Channel.GetStagiairesListAsync(fichierExcel);
        }
        
        public AGA.Common.DTO.Models.Stagiaire[] GetStagiairesPfeList() {
            return base.Channel.GetStagiairesPfeList();
        }
        
        public System.Threading.Tasks.Task<AGA.Common.DTO.Models.Stagiaire[]> GetStagiairesPfeListAsync() {
            return base.Channel.GetStagiairesPfeListAsync();
        }
        
        public AGA.Common.DTO.Models.Collaborateur[] GetCollaborateursNonEligiblesList() {
            return base.Channel.GetCollaborateursNonEligiblesList();
        }
        
        public System.Threading.Tasks.Task<AGA.Common.DTO.Models.Collaborateur[]> GetCollaborateursNonEligiblesListAsync() {
            return base.Channel.GetCollaborateursNonEligiblesListAsync();
        }
    }
}
